### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by junior201110** [ogaclejapan/SmartTabLayout#102]
When I go build my project, the android studio return this error and don`t start my app. What I can make to fix this? 

12-01 14:10:07.362 6441-6441/viewup.com.japesquisoteste E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: viewup.com.japesquisoteste, PID: 6441
                                                                          android.view.InflateException: Binary XML file line #18: Error inflating class com.ogaclejapan.smarttablayout.SmartTabStrip
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:616)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                              at viewup.com.japesquisoteste.fragments.FragmentNews.onCreateView(FragmentNews.java:34)
                                                                              at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                                              at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                              at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                                                              at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                                              at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
                                                                              at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
                                                                              at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
                                                                              at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
                                                                              at android.view.View.measure(View.java:17547)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                              at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                              at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                              at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                              at android.view.View.measure(View.java:17547)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                              at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                              at android.view.View.measure(View.java:17547)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                              at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                              at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                              at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                              at android.view.View.measure(View.java:17547)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                              at android.view.View.measure(View.java:17547)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                              at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                              at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                              at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                              at android.view.View.measure(View.java:17547)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                              at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
                                                                              at android.view.View.measure(View.java:17547)
                                                                              at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
                                                                              at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
                                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
                                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          	at android.os.Loo
12-01 14:10:08.950 6441-6441/? I/Process: Sending signal. PID: 6441 SIG: 9

**Comment by ogaclejapan** [comment]
Hi, @junior201110 

Please share the Layout and Code.

**Comment by ogaclejapan** [comment]
There is no response... : (
So, close this issue.

**Comment by junior201110** [comment]
o I'm sorry
 i'm have been traveling on  days
and i can't to share my code now, but when i get back 
i go shared with you the bug.
