### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by renatoOliveira25** [ogaclejapan/SmartTabLayout#284]
When I run the app, I get the following error message.

I'm not an expert, but what I see is that ViewPager cannot be Inflated, can anyone help me?

2019-04-08 20:14:03.332 6519-6519/com.analytic.abas E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.analytic.abas, PID: 6519
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.analytic.abas/com.analytic.abas.Activity.MainActivity}: android.view.InflateException: Binary XML file line #40: Binary XML file line #40: Error inflating class androidx.viewpager.widget.ViewPager
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.view.InflateException: Binary XML file line #40: Binary XML file line #40: Error inflating class androidx.viewpager.widget.ViewPager
     Caused by: android.view.InflateException: Binary XML file line #40: Error inflating class androidx.viewpager.widget.ViewPager
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.viewpager.widget.ViewPager" on path: DexPathList[[zip file "/data/app/com.analytic.abas-hHMzVIW2jIl7i0bRgGYUSQ==/base.apk", zip file "/data/app/com.analytic.abas-hHMzVIW2jIl7i0bRgGYUSQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.analytic.abas-hHMzVIW2jIl7i0bRgGYUSQ==/split_lib_resources_apk.apk", zip file "/data/app/com.analytic.abas-hHMzVIW2jIl7i0bRgGYUSQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.analytic.abas-hHMzVIW2jIl7i0bRgGYUSQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.analytic.abas-hHMzVIW2jIl7i0bRgGYUSQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.analytic.abas-hHMzVIW2jIl7i0bRgGYUSQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.analytic.abas-hHMzVIW2jIl7i0bRgGYUSQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.analytic.abas-hHMzVIW2jIl7i0bRgGYUSQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.analytic.abas-hHMzVIW2jIl7i0bRgGYUSQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.analytic.abas-hHMzVIW2jIl7i0bRgGYUSQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.analytic.abas-hHMzVIW2jIl7i0bRgGYUSQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.analytic.abas-hHMzVIW2jIl7i0bRgGYUSQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.analytic.abas-hHMzVIW2jIl7i0bRgGYUSQ==/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:606)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.analytic.abas.Activity.MainActivity.onCreate(MainActivity.java:23)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
2019-04-08 20:14:03.335 6519-6519/com.analytic.abas E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.analytic.abas-hHMzVIW2jIl7i0bRgGYUSQ==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:727)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
        at android.app.LoadedApk.getResources(LoadedApk.java:1032)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5749)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        		... 6 more

**Comment by renatoOliveira25** [comment]
I get it... in the e.g. the autor use the androidx ViewPager, just change to **android.support.v4.view.ViewPager**
